const galleryArray = [
  {
    name: "Modern and Contemporary Art",
    theme: "Social Realism",
    id: 1320,
    image: "https://nrs.harvard.edu/urn-3:HUAM:75998_dynmc",
    description: "The seismic social, political, and economic events of the early twentieth century—the Mexican and Russian revolutions, World War I and its aftermath, the Spanish Civil War, the Sino-Japanese War, the rise of Fascism, and the Great Depression—radicalized many artists, leading them to organize international networks, federations, congresses, and unions as forums through which to rethink the form, content, and function of art in uncertain modern times.\r\nBy the early 1930s, many leftist artists had abandoned abstraction and other modernist idioms in an effort to create what the art historian and social critic Meyer Schapiro would term a new “public use of art.” They employed easily legible realist, narrative, and reportage approaches to image making that focused on the daily life, social concerns, and political activities of the working class. At stake was the proposition that the modern artist is a laborer who participates in social action and uses art as an instrument of persuasion and dissent.\r\nThe models for this radical approach to contemporary “history painting” or “document pictures” as they were sometimes called arose from an earlier generation of American realism, interwar realism in Russia and Germany, and the work of the Mexican muralists. It also drew from the rising cultural force of mass media. Documentary photography and film played a particularly critical role in the visual culture of the 1930s and 1940s, serving as media for artistic expression, source material, and the basis for a broadly shared aesthetic rooted in eyewitness journalism.\r\nThe Harvard Art Museums’ collection of American social realism and related material is especially strong in the works on paper that were pivotal in the movement."
  },
  {
    name: "Early Chinese Art",
    theme: "Arts of Ancient China from the Neolithic to the Bronze Age",
    id: 1740,
    image: "https://nrs.harvard.edu/urn-3:huam:DDC112427_dynmc",
    description: "As one of the world’s oldest continuous civilizations, China has artistic traditions dating back more than seven thousand years. From Neolithic ceramics to archaic jades and ritual bronzes, the arts of China’s ancient past demonstrate technical sophistication, brilliant craftsmanship, and the frequent implementation of large-scale production methods, especially in objects created for the elite.\r\nEven before the widespread use of metal implements, Neolithic cultures in China produced fine pottery and carved jades, the most elaborate of which were buried in the graves of important personages. A belief in the afterlife and in the ability of deceased forebears to exert influence over life in the present world led to the practice of ancestor worship, especially among those in power in Bronze Age China. To appease ancestral spirits, ritual offerings of food and wine were presented in highly decorated bronze vessels; these vessels were later interred in their owners’ tombs, along with numerous other grave goods designed for use in the afterlife. The demand for bronze vessels reached its peak during the Shang (c. 1600–c. 1050 BCE) and Zhou (c. 1050–256 BCE) dynasties. Jades used for either ritual or ornamental purposes were buried with the dead from the late Neolithic period (c. 5000–c. 2000 BCE) to the Han dynasty (206 BCE–220 CE). The creation of these intricate objects required the control of vast quantities of raw materials and skilled labor—something possible only for the ruling class. Bronzes and other tomb objects required for religious rites thus came to symbolize the power of the elite. \r\nDesigned as ritual objects, the works in this gallery are now appreciated both for their aesthetic qualities and for what they reveal about China’s illustrious past, as it evolved from a series of Neolithic settlements to clusters of powerful kingdoms, and eventually to a unified empire."
  },
  {
    name: "European and American Art, 17th–19th century",
    theme: "The Silver Cabinet: Art and Ritual, 1600–1850",
    id: 2340,
    image: "https://nrs.harvard.edu/urn-3:HUAM:VRS14203_dynmc",
    description: "For centuries, silver was among the most revered and highly valued materials in Britain. Shipped across the Atlantic from the vast mines of Central America, silver was used to craft a variety of sacred and secular objects, from cups and salvers to medals and coins. Between 1600 and 1850, silver objects also figured prominently in a wide range of religious and social rituals, from the communion service to the taking of tea.\r\n\r\n\r\nThis gallery displays pieces of silver crafted for four of these rituals, each of which required specific forms and styles of ornamentation. Ritual objects from the religious altar occupy the left side of the cabinet. The center section presents elaborately ornamented dining wares decorated to elicit attention. Assembled on the right are exotic objects used in tea drinking, and in the rightmost section, one finds cups and tankards from Harvard’s High Table, the exclusive area where privileged students and senior faculty dined in the seventeenth and eighteenth centuries.\r\n\r\n\r\nThe silver on view in each section is linked by shared stylistic attributes and decorative motifs, pointing to the relationship between design and ritual. Between the seventeenth and nineteenth centuries in Britain, the art of crafting silver was a culturally embedded practice informed by the ideological questions, patterns of human behavior, and larger debates about the power of objects that animated all of the rituals in which silver objects played a part."
  },
  {
    name: "Ancient Mediterranean and Near Eastern Art",
    theme: "Classical Sculpture",
    id: 3200,
    image: "https://nrs.harvard.edu/urn-3:HUAM:756755",
    description: "White marble and nude bodies signify Classical art unlike any other material and form. Centuries of collecting and emulating Classical sculpture established the notion of its timeless perfection. As awareness of other artistic traditions has increased and as modern and contemporary artists have explored radically different approaches, this notion has become more tenuous. The greater critical distance actually benefits our understanding of Classical art, allowing us to recognize its time-bound nature and inviting us to appreciate it on its own terms.\r\nThe ancient marble sculptures in this colonnade have often been seen as examples of Greek art, but they are in fact of Roman origin and represent an early phase in a long history of reception. Many of the Greek sculptors of the fifth and fourth centuries BCE praised by ancient authors—Phidias, Polykleitos, Skopas, Praxiteles, Lysippus—worked in bronze and in gold and ivory, materials less enduring than stone. Most of their sculptures are lost. What remains are numerous Roman marble statues in Greek style. Traditionally, these have been classified as copies of famous Greek works, but the creativity of the Roman period sculptors should not be underestimated. As they carved statuary for an audience that admired Greek intellectual culture and art, they went beyond simple copying, creating variants and new sculptural types specifically for Roman tastes and settings, such as temples, theaters, bath buildings, houses, and villas.\r\nThis gallery also includes smaller works. Representations of the female body across the ages provide a counterpart to the Greek preoccupation with the male nude. Coins with elaborate designs represent Greek sculptural originals. Several are signed, drawing attention to their artistic authorship, an idea that was more prominently expressed in Greek art than elsewhere in antiquity. Bronze statuettes illustrate the development of styles from the Greek Bronze Age to Roman times."
  },
  {
    name: "Ancient Mediterranean and Near Eastern Art",
    theme: "Ancient Egypt: Art for Eternity",
    id: 3740,
    image: "https://nrs.harvard.edu/urn-3:HUAM:INV011632_dynmc",
    description: "Durability was a key characteristic of Egyptian sculpture. Placed in temples and tombs, the statues of gods, kings, and individuals were intended as sites where the divine or human essence could reside in perpetuity and receive cult and offerings. Sculpture therefore played an important intermediary role between the worlds of the human and the divine and those of the living and the dead. The use of hard stones, the sturdy forms of most stone statuary, and the dry climate, which benefits the preservation of wooden statuary, have contributed to the remarkable survival of sculpture in a variety of media. The general appearance of Egyptian sculpture endured as well. Because statues and reliefs were closely tied to religious beliefs and rituals, established forms continued over millennia and through periods of foreign rule. Conscious revivals of older styles followed times of unrest (including the “intermediate periods” after the Old, Middle, and New Kingdoms). The effective formal solutions and high-quality carving of Egyptian sculpture inspired sculptors in neighboring regions, especially in sixth-century BCE Greece. Through its impact on Greek art, Egyptian sculpture helped lay the foundations for art in the Western tradition.\r\nThis gallery comprises sculptures, paintings, and textiles from four millennia, from the Old Kingdom (c. 2649–2100 BCE) to the advent of Islam. Objects of the Ptolemaic period (323–30 BCE) demonstrate the strength of local artistic traditions, which existed alongside Greek art forms introduced by the new rulers of Macedonian origin. For the following Roman period, mummy portraits indicate both continuity and change in their combination of Egyptian funerary rites with portraiture in Greco-Roman style. The exceptional preservation of the paintings—and of traces of paint on sculpture—is owed again to the Egyptian climate, as is the survival of textiles. Fragmentary clothing and hangings provide glimpses of everyday life in late Roman and early Byzantine Egypt."
  },
  {
    name: "Modern and Contemporary Art",
    theme: "Art in Germany Between the Wars",
    id: 1520,
    image: "https://nrs.harvard.edu/urn-3:HUAM:LEG273767",
    description: "Who Owns the World? Art and Politics in the Weimar Republic Selections from the Busch-Reisinger Museum and the Merrill C. Berman Collection\r\nThe year 2019 marks not only the centennial of the founding of the Bauhaus school of art and design, but also the official founding of Germany’s Weimar Republic (1919–33). In the midst of upheaval in Germany after World War I, artist groups formed with the aim of transforming society. Despite their radical beginnings, however, many of these groups fizzled by the mid-1920s amid relative stabilization. This installation introduces artists with a range of stylistic approaches from across the country—Berlin, Karlsruhe, Hannover, Cologne, and Düsseldorf—who foregrounded class struggle and the material and cultural circumstances of workers’ lives well into the final years of Germany’s first democracy. Many of the artists featured here were associated with the German Communist Party or other radical organizations on the German Left. \r\nAs exemplified by the portfolio Hunger at the center of this gallery, printmaking played a key role in the dissemination of ideas. In an age of new technologies, many artists nonetheless remained committed to painting and drawing as a means to unite artistic form with left-wing politics. Socially critical art of the Weimar period has often been considered synonymous with the \"left wing\" of New Objectivity (Neue Sachlichkeit), as exemplified in the work of Otto Dix and George Grosz seen here. A number of key artists, whose work is also on view, fall outside this category, however, or actively challenged it at the time. \r\nIn The Art Lover (1937), by American social realist Mervin Jules, a bald, bespectacled man—a stereotype of ruling-class wealth and privilege—views a painting of demonstrating workers in a smoke-filled industrial landscape. This painting-within-a-painting provides a point of departure: how is a painting of a workers’ demonstration, one likely made to encourage class consciousness, to be understood by its viewers? By a bourgeois aesthete? In a museum? What do the works of art in this gallery have to tell us today about art’s role in society? "
  },
  {
    name: "Modern and Contemporary Art",
    theme: "The Sixties Experiment/Multiple Strategies",
    id: 1100,
    image: "https://nrs.harvard.edu/urn-3:HUAM:DDC244506_dynmc",
    description: "Multiple Strategies\r\n\r\nAs contemporary art was increasingly commercialized and institutionalized in the 1960s, some artists, taking up the legacy of Marcel Duchamp’s iconoclasm, stopped making objects and began to use language as their primary medium. Others focused on creating new means of displaying and distributing art to expand its circulation and accessibility, and used ephemeral media such as performance to produce works that could not be packaged and sold. Photography, as a way to record such works, became a crucial tool for artists. At the same time, diaristic approaches to documentary camerawork, with an emphasis on the subjectivity of the artist, gained currency.\r\nRelated to this enthusiasm for photography, and to a renewed interest in printmaking and cast sculpture, was the production of multiples, identical versions of the same artwork in limited editions. Multiples served as both art objects and vehicles for the distribution of art, with the intention to democratize it, and many were produced as components of performances. The Harvard Art Museums hold a near-comprehensive set of multiples by the impresario of postwar German conceptual art, Joseph Beuys; an extensive collection produced by Fluxus artists based in New York; and a complete set of books made by the Los Angeles pop artist Ed Ruscha. These objects, widely influential during the 1960s, demonstrate the seemingly boundless range of multiples production.\r\nAs the decade waned, so did much of the optimism about the potential of radical art practices. Nonetheless, 1960s art reverberated in subsequent years and continues to do so today, as artists grapple with their role in effecting social and political change, the status of art in a world of rapid technological innovation, and voracious commodification."
  },
  {
    name: "European Art, 19th–20th century",
    theme: "Collection of Maurice Wertheim, Class of 1906",
    id: 1220,
    image: "https://nrs.harvard.edu/urn-3:HUAM:DDC252060_dynmc",
    description: "Maurice Wertheim (1886–1950), Harvard Class of 1906, was an investment banker from New York. He began amassing his renowned collection in the 1930s, acquiring masterpieces by famed artists like Edgar Degas, Claude Monet, and Pierre-Auguste Renoir, as well as contemporary figures such as Aristide Maillol, Henri Matisse, and Pablo Picasso. His interest in modern art was informed by recommendations from advisors, who included Alfred M. Frankfurter, editor of the highly read periodical Art News, and Paul J. Sachs, associate director of the Fogg Art Museum from 1923–45.\r\nWertheim’s decision to focus on nineteenth- and twentieth-century art also derived from practical considerations. Like other American collectors purchasing art after World War I, Wertheim perceived that art from this era was both critically acclaimed and financially accessible. An added benefit, for him, was the fact that its scale and varied styles were well suited to his modern penthouse apartment on the Upper East Side of New York City, where the works were first installed.\r\nWertheim bequeathed his collection to Harvard, to be studied and enjoyed by students and scholars, with the stipulation that it be shown together in a single gallery."
  },
  {
    name: "European and American Art, 17th–19th century",
    theme: "Centuries of Tradition, Changing Times: Art for an Uncertain Age",
    id: 2100,
    image: "https://nrs.harvard.edu/urn-3:HUAM:770509",
    description: "This gallery brings together examples of the new materials, technologies, and ways of seeing that animated the art world in the mid-19th century. Painters, sculptors, and photographers developed innovative techniques to respond to a world rendered unfamiliar by urbanization and industrialization. Oil painting remained a leading expressive medium, but painters adapted centuries of tradition to the turbulent, changing times in which they lived. Some turned to the landscape to offset the trauma of the modern city, while others took an interest in the emerging psychology and science of perception. For American painters who faced the trauma of civil war, realism offered the best path to take stock of a nation devastated by bloodshed, factionalism, and social unrest.\r\nThe mid-19th century also witnessed the advent of photography. Invented in France and England and widely adapted by 1839, this radical image-making technology astonished early audiences and made formerly elite forms like portraiture available to wide swaths of the population. Photography put pressure on every genre of art making, even as it drew from longstanding art historical conventions. The works in the gallery reflect the influence of this new medium, as well as the new ways of seeing and interpreting the world it brought about."
  },
  {
    name: "European and American Art, 17th–19th century",
    theme: "Rococo and Neoclassicism in the Eighteenth Century",
    id: 2220,
    image: "https://nrs.harvard.edu/urn-3:HUAM:DDC252612_dynmc",
    description: "Two styles prevailed in European art of the eighteenth century: rococo, associated with the reign of French king Louis XV (1715–1774), and neoclassicism, which emerged mid-century. The term rococo is a combination of the French word rocaille—a style of ornament with an elaborate, often asymmetrical conflation of natural elements, especially plants, stones, and shells—and the Italian word barocco, which refers to the baroque style, characterized by exuberant ornamentation and dramatic action. Artists of this era favored a palette of light hues; they frequently alluded to contemporary dance and theater; and particularly in the realm of decorative arts, they borrowed elements from Chinese art that was being exported to Europe. These traits led to the characterization of rococo art as lighthearted and fantastical, despite its continued consideration of sober, moral subjects—such as the Virgin’s Purification in Corrado Giaquinto’s painting at the center of this gallery—and its studied attentiveness to tradition.\r\nNeoclassicism, a style based on the art of ancient Greece and Rome, developed in tandem with archaeological excavations at Herculaneum and Pompeii toward the middle of the century. The availability of extensive new evidence of the arts of antiquity—coupled later in the century with the scholarly writings of Johann Joachim Winckelmann (1717–1768), who distinguished styles in the art of different ancient civilizations—triggered a demand for greater accuracy in the visual representation of ancient subjects. Artists responded to this necessity by importing into their compositions classical forms and objects that they had seen in ancient collections or knew through prints. Young collectors from northern European countries sought to expand their knowledge of antiquity by traveling through Italy on an extensive trip known as the Grand Tour. While visiting ancient sites and museums, they purchased antiquities and contemporary art for their burgeoning private collections."
  },
  {
    name: "Ancient Mediterranean and Near Eastern Art",
    theme: "Ancient Near Eastern Art in the Service of Kings",
    id: 3440,
    image: "https://nrs.harvard.edu/urn-3:HUAM:VRS10353_dynmc",
    description: "The world’s first powerful kingdoms arose in ancient Mesopotamia in the third and second millennia BCE, centered on the cities of Ur, Akkad, and Babylon. Monumental architecture grew with the rulers’ ambitions, incorporating elaborate sculpted and painted decoration. Administrative needs increased with the size of the territory, resulting in complex systems of record-keeping and the thriving of a form of miniature art: personal seals with carved designs. Widely divergent in scale, architectural decoration and seals shared many of the same motifs: encounters with animals and monsters; scenes of courtly life, such as the banquet and the hunt; and the worship of deities. Timeless formulae recurred not only across media but also in different regions and periods.\r\nThis gallery presents objects from Anatolia (modern Turkey) in the west to Central Asia in the east, and dating from the Sumerian to the Sasanian periods, from the third millennium BCE to the first millennium CE, with a special focus on first-millennium BCE Iran. The Achaemenid Persian reliefs on the right — like the Neo-Assyrian example just outside this gallery — are prime examples of art in the service of kingship, carved by sculptors whose individual identity mattered little. Assyrian and Persian royal imagery had a lasting impact, for example in promoting the lion as a potent symbol of power. Ideas of kingship were also expressed in coinage, first in Anatolian Lydia and the Persian Empire, and later, after Alexander of Macedon’s (356–323 BCE) conquest of Asia, in the coins of his successors. Near Eastern inspiration extended to many other areas as well, from alphabetic writing and renderings of the human figure, to a menagerie of monsters. The mostly Iranian bronzes on display here show the importance of animal forms in ancient Near Eastern art, revealing the development of distinctive styles with varying degrees of abstraction."
  },
  {
    name: "Art from Islamic Lands",
    theme: "The Middle East and North Africa",
    id: 2550,
    image: "https://nrs.harvard.edu/urn-3:HUAM:DDC252363_dynmc",
    description: "From its seventh-century origin in the Arabian Peninsula, Islam expanded outward with extraordinary speed, through conversion and conquest. Within a scant two centuries, it had spread eastward and westward across ancient cultural centers to establish dominions linking southern Europe, northern Africa, and southern and central Asia in the new faith.\r\nThe visual arts of Islam have been colored by a profound reverence for sacred texts, especially the Qurʾan, which Muslims consider the literal word of God, revealed to the Prophet Muhammad in the Arabic language. As the primary vehicle for preserving and disseminating this text, the Arabic script was elevated to the level of calligraphy and became Islam’s quintessential visual expression. Through its ability to state meaning literally, Islamic calligraphy obviated the need for a complex pictorial symbolism.\r\nOver the centuries, a wealth of decorative modes developed in Islamic art. A deep interest in abstract order is evidenced by Islamic contributions to mathematics and by the proliferation of geometrically structured vegetal and interlace patterns in art and architecture. Although Islamic prohibitions against idolatry discouraged the representation of living creatures for religious purposes, artists in various lands developed a rich repertoire of figural imagery to illustrate secular texts, to represent the personalities and activities of the court, and to embellish utilitarian objects.\r\nDespite decades of usage, the term “Islamic art” remains ambiguous. It is used here to designate works of art made by or for Muslims, or works of art produced in lands where the rulers or the majority of the population followed or follow the faith of Islam. This installation offers a glimpse of Harvard’s holdings of Islamic art, ordered according to a flexible chronology: the early Islamic era (650–1050); the medieval era (1050–1450); and the early modern era (1450–1800). Selected to demonstrate continuity, these objects nevertheless speak eloquently of the cultural diversity in Muslim lands."
  },
  {
    name: "Ancient Mediterranean and Near Eastern Art",
    theme: "Roman Art",
    id: 3700,
    image: "https://nrs.harvard.edu/urn-3:HUAM:DDC231389_dynmc",
    description: "The Roman Empire encompassed a multitude of disparate peoples throughout the Mediterranean world. From the first century BCE to the fifth century CE, the inhabitants of the empire were connected by the material elements of Roman life—from the monumental (baths, amphitheaters, forums, and aqueducts) to the personal (ceramics, brooches, and household gods). Roman customs and visual culture drew not only on Greek traditions but also on those of the Etruscans, Iberians, Celts, Egyptians, and others who were united under Roman rule. In religion, native Italian traditions, such as the offering of anatomical votives, were preserved alongside newly encountered beliefs. Evolving practices sometimes combined the characteristics and functions of deities, such as the Egyptian Isis with the Roman Venus, who was essentially the Greek Aphrodite. Roman influence in laws, individual representation, coins, and decorative motifs continued into the Byzantine and medieval periods.\r\nEmbellished with the attributes of deities, heroes, and conquerors, the portraits of Roman emperors and their families were prominent on coins. Their statues were set up in forums throughout the empire and venerated in shrines dedicated to the imperial cult, which helped to reinforce the loyalty of the common people, many of whom would never personally see their ruler. Wealthy private citizens also commissioned statues of themselves, in some cases following imperial models, but funerary sculpture—including urns, sarcophagi, and especially inscriptions—was the primary medium for individual commemoration. A common scene depicted in Roman funerary reliefs, wall paintings, mosaics, and literature was the banquet, where the diners would recline to eat while they were entertained by music, dancing, or even physical contests. The luxury tableware left behind is a testament to the decadence of the Roman banquet, which has inspired artistic representations from the Renaissance to this day. "
  },
  {
    name: "Medieval Art",
    theme: "Medieval Times Art",
    id: 2440,
    image: "https://nrs.harvard.edu/urn-3:HUAM:73150_dynmc",
    description: "The European Middle Ages lasted for a millennium after the fall of the Roman Empire (c. 450). Most of the objects in this gallery date to the High Middle Ages (1100–1400), a period of great political, intellectual, and economic growth. During this time, the regions of England, France, Germany, and Italy, among others, began to take shape as political entities, and the first universities were founded in Oxford, Paris, and Bologna. Economies became less agrarian and more mercantile, and growing cities drew artisans and merchants who stimulated trade. Exchange developed between the eastern Byzantine Empire (c. 330–1453) and western Europe with the trafficking of precious materials, books, and knowledge. Many of the artistic traditions of Byzantium, centered in Constantinople, were emulated in the West, as evidenced by objects here. Wealth spread to a burgeoning middle class, and individual patrons commissioned works of art for private devotion.\r\nThrough the patronage of monasteries, parish churches, and cathedrals—among the wealthiest and most powerful institutions of their time—ornate objects were produced for ecclesiastical purposes. Censers, reliquaries, and crosses, used to celebrate Mass, were made of rare and costly materials, befitting the stature of the saints and God.\r\nChurches and public spaces were elaborately decorated. Some objects, such as depictions of the Virgin and Child, could be carried in procession or placed in chapels for prayer or contemplation. Several of the works in this gallery were once architectural elements or parts of larger objects. Their fragmentary nature reminds us of both the complex artistic programs to which they once belonged and the way museums necessarily separate art from its original context."
  },
  {
    name: "European Art, 13th–16th century",
    theme: "Art and Image in Europe",
    id: 2500,
    image: "https://nrs.harvard.edu/urn-3:HUAM:DDC252603_dynmc",
    description: "For centuries, artists were tasked with painting images (icons) of Christ and the Virgin Mary. Viewers believed that these likenesses had been created miraculously, and artists were able to give their work a sense of authenticity by adhering closely to images that were reputedly painted by Saint Luke, or by some other holy means. Over the centuries, Byzantine icons stayed true to these early images. Although there was considerable exchange between Europe and the East, the sack of Constantinople by Western European and Venetian crusaders in 1204 brought a wave of artwork from the Byzantine capital to Europe. Early Italian painters initially remained faithful to Byzantine models, but they soon broke away from the tradition, introducing personal and regional styles to their work. \r\nDuring the Renaissance, artistic practice became more codified through treatises as well as through critical awareness of differences between artists and regional styles. Around the middle of the sixteenth century, Giorgio Vasari, the Italian artist and art historian, wrote a magisterial history of the lives of Italian artists that assessed Italian painting from the previous three centuries.\r\nOne of the most important artistic categories was the altarpiece. The works in this gallery testify to the wealth of materials and techniques employed by carpenters, painters, and sculptors in making these sacred objects. In early panel paintings and polychromed wood sculpture, gold leaf and punched detail were employed to decorate the robes of holy figures. The rich and dense quality of prized blue pigment, which was derived from lapis lazuli sourced in Afghanistan, was often used to depict the Virgin’s cloak. Costly gold was tooled and polished to create luminous, unworldly backgrounds; over time, these gradually gave way to ultramarine skies.\r\nThe movement of material goods from East to West anticipated the traffic in works of art between the Old and New World. Itinerant objects like the ivory Crucified Christ, a Netherlandish-type crucifix possibly made in the Philippines by Chinese craftsmen for Catholic patrons in New Spain, remind us that the Renaissance’s flowering of the arts was fueled in part by unprecedented global exploration and growing colonial ambitions."
  },
  {
    name: "European Art, 13th–16th century",
    theme: "The Renaissance",
    id: 2540,
    image: "https://nrs.harvard.edu/urn-3:HUAM:DDC231549_dynmc",
    description: "European art was greatly influenced by the rediscovery of ancient sculpture and the renewed interest in classical texts. Through reproductive media such as books, prints, medals, and statuettes, antiquarian knowledge spread north and south of the Alps. In these galleries, the revival of antiquity can be seen in small-scale objects that circulated between Italian and northern courts and in paintings of mythological themes. Antiquity could be used in allegorical portraiture and in other domestic contexts; mythological stories could also serve as moralizing reminders in the home.\r\nConventions associated with earlier religious art, such as the triptych format for altarpieces, remained, and many artists took as much inspiration from the natural world as they did from antiquity. The works on display here reveal a growing appreciation for landscape painting; for instance, Filippo Lippi uses a landscape to establish an ascetic frame for the penitent St. Jerome, and an Arcadian setting is featured in the pastoral idyll attributed to Titian. Small-scale paintings such as these were often admired in the context of the studiolo, a private domestic space where precious possessions—books, coins, drawings, prints,sculptures, natural curiosities, and fine scholarly paraphernalia—were displayed for contemplation.\r\nThis period also witnessed the slow disappearance of artistic guilds and the increased emphasis on personal style, whether revealed in finely crafted drawings or in the energetic strokes of a painter’s brush. Artists were often called to serve foreign courts, and their work came to reflect these new contexts and environments. The vibrant exchange between Spain and Italy is evident in the large wooden reredos, or altar backdrop, the design of which demonstrates an awareness of Roman architecture and other artistic currents.\r\nAround the turn of the fifteenth and sixteenth centuries, Florence came under the spell of the prophecies of the charismatic preacher Savonarola, and in the north, Martin Luther brought about ecclesiastical reform, more widely termed the Reformation."
  },
  {
    name: "East Asian Art",
    theme: "East Asian Painting and Decorative Arts",
    id: 2600,
    image: "https://nrs.harvard.edu/urn-3:HUAM:73727_dynmc",
    description: "The Early Modern Era in South Asia\r\n\r\nBy the end of the medieval era, Muslims had established numerous principalities across the Indian subcontinent—notably in the Punjab, Bengal, and the Indo-Gangetic plain, and in the southern plateau region known as the Deccan. Art of the Deccani Sultanates (1347–1686) is renowned for robust forms and designs, as seen here in the dish and incense burner. The rise of the Mughal dynasty (1526–1857) eventually brought most of India under the control of a single Muslim polity with a highly sophisticated court culture. During the seventeenth century, Mughal art developed a refined aesthetic, blending Persian, Indian, and European elements and techniques. It also sparked an artistic renaissance at Hindu courts in Rajasthan and the Punjab Hills.\r\nIn many ways, South Asia proved a remarkable arena for the growing internationalism of the early modern era. India had long been a focal point in overland and sea trade, and its strategic value increased significantly with the rise of the European trading companies in the sixteenth and seventeenth centuries."
  },
  {
    name: "Ancient Mediterranean and Near Eastern Art",
    theme: "Ancient Greece in Black and Orange",
    id: 3400,
    image: "https://nrs.harvard.edu/urn-3:HUAM:DDC102627_dynmc",
    description: "Ancient Greece had its share of well-known painters, men named Polygnotos, Mikon, Parrhasios, Zeuxis, Apollodoros, Apelles, and Nikias. Ancient authors talk about their works, innovations, and rivalries, but not a single panel or wall painting by one of these artists has survived the millennia. Instead, countless small-scale images have endured in a sturdier medium: painted pottery. Painters of pots are not mentioned in ancient sources, and they clearly did not have the same prestige as their colleagues working on a larger scale. Some signed their names, however, and the products of workshops based in Corinth and Athens, especially, were widely exported. In modern scholarship, painted “vases” — as they tend to be called — have received significant attention, and rigorous connoisseurship has identified numerous artistic personalities. The large corpus of painted pottery supplies valuable information on the development of Greek visual representation.\r\nThis gallery shows major trends in Greek vase painting of the Archaic (600–480 BCE) and Classical (480–323 BCE) periods, including contributions by different city-states and the Greek colonies of South Italy. As in sculpture, the human figure takes center stage. Subject matter ranges from the mythological to the everyday. Although most well-preserved examples come from tombs, painted pottery was essentially utilitarian, and its intended function should be considered in any examination of the decoration. Many shapes belong to the symposion, the communal drinking party that was a central institution in ancient Greece. The imagery on the vessels would have expressed and shaped the concerns and identities of broad sections of the population, providing the modern viewer with a rare glimpse of how regular people saw the world. Coins, too, take us right into the midst of ancient Greek life, including industry and trade. In emblematic fashion, they speak to the individual identities of the city-states and how these could be reinforced by mythology."
  },
  {
    name: "Early Chinese Art",
    theme: "Arts of Ancient China from the Bronze Age to the Golden Age",
    id: 1600,
    image: "https://nrs.harvard.edu/urn-3:HUAM:61515_dynmc",
    description: "The Zhou was a powerful state in the region of modern-day Shaanxi province in northern China. It came to power after overthrowing the area’s Shang rulers in the mid-11th century BCE. In an effort to establish its cultural legitimacy, the Zhou adopted its predecessors’ religious rites; the result was the uninterrupted manufacture of the kinds of ritual bronze vessels and jade implements that had been the sacred tomb furnishings of the Shang elite. In the eighth century BCE, however, attacks by nomadic invaders forced Zhou rulers to abandon their capital in modern-day Xi’an, Shaanxi province, and flee eastward to present-day Luoyang, Henan province; they never again controlled a unified state. This move marks the division between the Western and Eastern Zhou periods, (c. 1050–771 and 770–256 BCE, respectively). The Eastern Zhou era saw a proliferation of luxury goods made of gold, silver, and lacquer being used as tomb objects, buried alongside the traditional bronzes and jades.\r\nBy the end of the Eastern Zhou period, ideas of the afterlife were shifting, and philosophers of the day inveighed against elaborate burials. By the Qin (221–206 BCE) and Han (206 BCE–220 CE) dynasties, as a belief in immortality took hold, both the structure and the contents of tombs began to change. Whereas Shang and Zhou tombs were essentially pits made to hold the dead and the items they would need in the afterlife, Qin and Han tombs were multi-chambered dwellings they could inhabit for all eternity. Ceramic replicas of vessels, architectural structures, domesticated animals, and servants replaced the precious objects (and living creatures) that had been interred in Bronze Age tombs. \r\nA protracted period of disunity followed the Han dynasty, before the country was again unified under imperial rule by the Sui (581–618) and Tang (618–907) dynasties. During the post-Han period, as China’s contact with foreign cultures to its west increased, tomb sculptures began to depict foreigners and exotic animals. Known as China’s Golden Age, the Tang dynasty was a long period of peace, prosperity, and territorial expansion, famous for its literary and artistic achievements."
  },
  {
    name: "Buddhist Sculpture",
    theme: "Buddhism and Early East Asian Buddhist Art",
    id: 1610,
    image: "https://nrs.harvard.edu/urn-3:HUAM:30679_dynmc",
    description: "In the late sixth century BCE, the northern Indian prince Siddhartha Gautama chose to abandon a life of worldly pleasure. He sought release from the suffering he believed inherent in samsara, the cycle of birth, death, and rebirth. Awakening to an understanding of existential suffering, he became the historical Buddha Shakyamuni, and his teachings, which offered both insights into samsara and a means to escape from it, became the basis of the philosophical and religious system now called Buddhism.\r\nThe religion’s earliest adherents believed the Buddha—literally, the “Awakened One”—to be a perfected mortal whose exemplary life of right living, proper meditation, and compassion demonstrated the path to awakening. Within three hundred years after the Buddha’s death, however, a new form of Buddhism arose. Mahayana Buddhism understood the Buddha as but one of many buddhas and posited the existence of numerous other deities—the most important of which are bodhisattvas, awakened beings who have postponed their release from samsara in order to aid their supplicants. By the first several centuries of the common era, Mahayana Buddhism came to flourish in East Asia, becoming one of the most important creative sources for art and architecture in China, Korea, and Japan.\r\nIn medieval East Asia, Buddhism was often referred to as the “teaching of images,” and it was primarily through the exchange of portable images, both painted and sculpted, that the religion was transmitted to the region. In Buddhist ritual practice, painted or sculpted images are treated not as representations of deities but as living deities themselves.\r\nThe works in this gallery are among the finest Chinese and Korean Buddhist sculptures in any American collection. They are drawn largely from the collection of Grenville L. Winthrop (1864–1943), a Harvard graduate of eclectic aesthetic predilections who held a special interest in early Chinese art."
  },
  {
    id: "",
    image: "https://i.imgur.com/hnKfDWW.png"
  }
]

module.exports = {
  galleryArray
}